# Conda environment specification. The dependencies defined in this file will

# be automatically provisioned for runs with userManagedDependencies=False.


# Details about the Conda environment file format:

# https://conda.io/docs/user-guide/tasks/manage-environments.html#create-env-file-manually


name: project_environment
dependencies:
  # The python interpreter version.

  # Currently Azure ML only supports 3.5.2 and later.

  - python=3.8
  - pip=21.2.4

  - pip:
      # Required packages for AzureML execution, history, and data preparation.

    - azureml-defaults
    - azure-keyvault-secrets
    - azure-identity
    - azure-servicebus
    
    - scikit-learn==0.22.2
    - xgboost==1.2.1
    - catboost==0.24.2

